discord_bot_key: "your-discord-bot-key"
guild_id: "your-guild-id"
voice_channel_id: "your-voice-channel-id"
icecast_url: "your-icecast-url"
icecast_status_url: "URL to status-json.xsl endpoint of your Icecast server"
